name: Build and Deploy Nginx

# Trigger the workflow manually with inputs
on:
  workflow_dispatch:
    inputs:
      ecs_cluster:
        description: 'ECS Cluster Name'
        required: true
        type: string
      ecs_service:
        description: 'ECS Service Name'
        required: true
        type: string
      ecr_repo:
        description: 'ECR Repository Name'
        required: true
        type: string
      ingestor_task_definition_family:
        description: 'Task Definiton'
        required: true
        type: string
      placeholder_values:
        description: 'Placeholder Values'
        required: true
        type: string
      aws_region:
        description: 'AWS Region'
        required: true
        type: string

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: arn:aws:iam::489994096722:role/akbar-oidc-github-action
        aws-region: ${{ github.event.inputs.aws_region }}
        mask-aws-account-id: 'no'

    - name: Login to Amazon ECR
      run: |
        aws ecr get-login-password --region ${{ github.event.inputs.aws_region }} | docker login --username AWS --password-stdin 489994096722.dkr.ecr.${{ github.event.inputs.aws_region }}.amazonaws.com

    - name: Replace placeholders in nginx.conf
      run: |
        PLACEHOLDER_VALUES="${{ github.event.inputs.placeholder_values }}"
        IFS=$'\n'       # Set the Internal Field Separator to newline
        for placeholder in $PLACEHOLDER_VALUES; do
          key=$(echo "$placeholder" | cut -d'=' -f1)
          value=$(echo "$placeholder" | cut -d'=' -f2-)
          sed -i "s|{{${key}}}|${value}|g" nginx.conf
        done

    - name: Build Docker image
      run: |
        docker build -t ${{ github.event.inputs.ecr_repo }}:latest .

    - name: Tag Docker image
      run: |
        docker tag ${{ github.event.inputs.ecr_repo }}:latest 489994096722.dkr.ecr.${{ github.event.inputs.aws_region }}.amazonaws.com/${{ github.event.inputs.ecr_repo }}:latest

    - name: Push Docker image to ECR
      run: |
        docker push 489994096722.dkr.ecr.${{ github.event.inputs.aws_region }}.amazonaws.com/${{ github.event.inputs.ecr_repo }}:latest
    
    - name: Download task definition
      run: |
        aws ecs describe-task-definition --task-definition ${{ github.event.inputs.ingestor_task_definition_family }} --query taskDefinition > task-definition.json
    
    - name: Deploy Amazon ECS task definition
      uses: aws-actions/amazon-ecs-deploy-task-definition@v1
      with:
        task-definition: task-definition.json
        service: ${{ github.event.inputs.ecs_service }}
        cluster: ${{ github.event.inputs.ecs_cluster }}
        wait-for-service-stability: true
